apiVersion: apps/v1
kind: Deployment
metadata:
  name: preapproval-api
  namespace: boa-agents
  labels:
    app: preapproval-api
    component: api-gateway
    tier: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: preapproval-api
  template:
    metadata:
      labels:
        app: preapproval-api
        component: api-gateway
        tier: web
    spec:
      containers:
      - name: api-gateway
        image: preapproval-api:latest
        imagePullPolicy: Never  # For local development
        ports:
        - containerPort: 8083
        env:
        - name: PORT
          value: "8083"
        envFrom:
        - configMapRef:
            name: boa-agents-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: preapproval-api
  namespace: boa-agents
  labels:
    app: preapproval-api
    component: api-gateway
spec:
  selector:
    app: preapproval-api
  ports:
  - port: 80
    targetPort: 8083
    protocol: TCP
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: preapproval-api-hpa
  namespace: boa-agents
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: preapproval-api
  minReplicas: 3
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
