apiVersion: apps/v1
kind: Deployment
metadata:
  name: boa-mcp
  namespace: boa-agents
  labels:
    app: boa-mcp
    component: mcp-server
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boa-mcp
  template:
    metadata:
      labels:
        app: boa-mcp
        component: mcp-server
        tier: backend
    spec:
      containers:
      - name: mcp-server
        image: boa-mcp:latest
        imagePullPolicy: Never  # For local development
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        envFrom:
        - configMapRef:
            name: boa-agents-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: boa-mcp
  namespace: boa-agents
  labels:
    app: boa-mcp
    component: mcp-server
spec:
  selector:
    app: boa-mcp
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
