apiVersion: apps/v1
kind: Deployment
metadata:
  name: risk-agent
  namespace: boa-agents
  labels:
    app: risk-agent
    component: ai-agent
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: risk-agent
  template:
    metadata:
      labels:
        app: risk-agent
        component: ai-agent
        tier: backend
    spec:
      containers:
      - name: risk-agent
        image: risk-agent:latest
        imagePullPolicy: Never  # For local development
        ports:
        - containerPort: 8081
        env:
        - name: PORT
          value: "8081"
        envFrom:
        - configMapRef:
            name: boa-agents-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: risk-agent
  namespace: boa-agents
  labels:
    app: risk-agent
    component: ai-agent
spec:
  selector:
    app: risk-agent
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: risk-agent-hpa
  namespace: boa-agents
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: risk-agent
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
